baseURL = "http://yayfrydayy.com/"
disablePathToLower = true
languageCode = "en-gb"
title = "YayFryDay"
theme = "stack"

[permalinks]
    posts = '/:title/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
